[package]
name = "sway-rename"
version = "0.1.0"
authors = ["Korbinian Maier <korbinian.maier@posteo.de>"]
edition = "2018"

[dependencies]
# swayipc = "2.7"
swayipc-async = "2.0.0-alpha.2"

tokio = { version = "0.3.2", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.7"
